<?php
/** @var \Brimar\Shipping\Block\Order\ShippingInfo $block */
$info = $block->getBrimarShippingInfo();
?>
<?php if (!empty($info)): ?>
    <div class="box-order-shipping-method">
        <strong class="box-title">
            <span><?= $block->escapeHtml(__('Brimar Shipping Options')) ?></span>
        </strong>
        <div class="box-content">
            <ul>
                <?php foreach ($info as $item): ?>
                    <li><?= $block->escapeHtml($item) ?></li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
<?php endif; ?>